In [41]:
import numpy as np

In [42]:
from numpy import genfromtxt

In [43]:
data = genfromtxt("DS1_C4_S1_Employee_Data_Challenge.csv ",delimiter = ",",skip_header = 1)
data

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

Task 1 
Calculate the average age of the employees in the IT firm

In [44]:
np.mean(data[:,1])

28.26

Task 2
Display the employee IDs/code of those employees who are over 25 years of age .Find the count of these employees

In [45]:
data[:,1]                  #age 

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

In [46]:
ind=data[:,1]>25
ind

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True])

In [47]:
emp_id = data[ind][:,0]

In [48]:
emp_id

array([ 2.,  3.,  4.,  5.,  6.,  7.,  9., 10., 11., 12., 14., 15., 16.,
       17., 20., 21., 22., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 37., 38., 40., 41., 42., 43., 44., 45., 46., 49., 50.])

In [49]:
len(emp_id)

38

In [50]:
#task 3
#Calculate the total number of employees who are in the age group of 30-35 years.
#Display the employee IDs/codes of these employees.

In [51]:
indx=(data[:,1]>=30) & (data[:,1]<=35)
indx

array([False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
       False, False, False,  True,  True])

In [52]:
count_emp =data[indx][:,0]                    #employee codes who are in the age group of 30-35

In [53]:
print("Employee codes who are in age group of 30-35 years are ",count_emp)           #employee ids

Employee codes who are in age group of 30-35 years are  [ 3. 10. 15. 16. 32. 41. 42. 43. 44. 45. 49. 50.]


In [54]:
print("Total number of employees who are in the age group of 30-35 are :",len(count_emp))

Total number of employees who are in the age group of 30-35 are : 12


In [72]:
from numpy import genfromtxt
shopping = genfromtxt("DS1_C4_S1_Shopping_Data_Challenge.csv",delimiter= ",",skip_header=1)
shopping

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [56]:
#Task1
#Display the details of the customers whose spending score is greater than 80. Also, display the total count of these customers.

In [74]:
indx = shopping[:,3]>80

In [75]:
spending_score = np.where(indx)
spending_score

(array([  1,   7,  11,  19,  25,  29,  33,  35,  41, 123, 127, 135, 141,
        143, 145, 149, 151, 155, 161, 163, 167, 173, 175, 179, 181, 183,
        185, 189, 193, 199], dtype=int64),)

In [76]:
details = shopping[spending_score]
print("Details of the customers whose spending score is greater than 80: \n",details)

Details of the customers whose spending score is greater than 80: 
 [[  2.  21.  15.  81.]
 [  8.  23.  18.  94.]
 [ 12.  35.  19.  99.]
 [ 20.  35.  23.  98.]
 [ 26.  29.  28.  82.]
 [ 30.  23.  29.  87.]
 [ 34.  18.  33.  92.]
 [ 36.  21.  33.  81.]
 [ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [156.  27.  78.  89.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [200.  30. 137.  83.]]


In [60]:
print("The total count of these customers whose spending is greater than 80 is :",len(details))

The total count of these customers whose spending is greater than 80 is : 30


In [61]:
#Task 2
#Extract and display the data of the customers who are 20 to 24 years of age.
#Note: This data helps analyze age-related expenditures.

In [62]:
index = (shopping[:,1]>=20) & (shopping[:,1]<=24)
age = np.where(index)
print("Data of the customers who are 20 to 24 years of age:\n",shopping[age])

Data of the customers who are 20 to 24 years of age:
 [[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


In [63]:
#task 3
#Display the IDs of the customers with the lowest annual incomes) and the highest annual income.

In [77]:
lowest_income = np.min(shopping[:,2])
lowest_income



15.0

In [78]:
index = shopping[:,2]==15

In [79]:
np.where(index)

(array([0, 1], dtype=int64),)

In [80]:
id_of_lowest_income = shopping[index][:,0]
print("IDs of the customers with the lowest annual incomes is",id_of_lowest_income)

IDs of the customers with the lowest annual incomes is [1. 2.]


In [81]:
highest_income = np.max(shopping[:,2])
highest_income

137.0

In [82]:
index2 = shopping[:,2]==137

In [83]:
np.where(index2)

(array([198, 199], dtype=int64),)

In [84]:
id_of_highest_income = shopping[index2][:,0]
print("IDs of the customers with the highest annual incomes is ",id_of_highest_income)

IDs of the customers with the highest annual incomes is  [199. 200.]


In [32]:
#Task 4
#Display the details of the customers who are less than 45 years of age, have an annual income greater than $35K, and 
#have a spending score greater than 75. How many such customers are there in the given data?

In [85]:
ind = (shopping[:,1] < 45) & (shopping[:,2] > 35) & (shopping[:,3] > 75)
ind

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True,

In [86]:
print("Details of the customers who are less than 45 years of age, have an annual income greater"
      "than $35K  and have a spending score greater than 75 are \n",shopping[ind])

Details of the customers who are less than 45 years of age, have an annual income greaterthan $35K  and have a spending score greater than 75 are 
 [[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]


In [35]:
index3 = np.where(ind)
index3

(array([ 41, 123, 125, 127, 135, 141, 143, 145, 149, 151, 153, 155, 157,
        161, 163, 167, 173, 175, 179, 181, 183, 185, 189, 193, 195, 199],
       dtype=int64),)

In [87]:
len(shopping[ind])

26

In [37]:
#Task 5
#During the Christmas season, the company wishes to offer random gift coupons valued between $10 and $50 to all its customers.
#Add a new column for the gift coupons in the existing data.
#Display the details of the customers after adding the new column.

In [39]:
shopping.shape

(200, 4)

In [88]:
gift_coupons = np.random.randint(10, 51, size=shopping.shape[0])

# Reshape the gift_coupons array to match the shape of the shopping array
gift_coupons = gift_coupons.reshape(-1, 1)

# Append the gift_coupons array as a new column to the shopping array
shopping = np.append(shopping, gift_coupons, axis=1)

print(shopping)

[[  1.  19.  15.  39.  23.]
 [  2.  21.  15.  81.  22.]
 [  3.  20.  16.   6.  44.]
 [  4.  23.  16.  77.  27.]
 [  5.  31.  17.  40.  27.]
 [  6.  22.  17.  76.  13.]
 [  7.  35.  18.   6.  20.]
 [  8.  23.  18.  94.  42.]
 [  9.  64.  19.   3.  15.]
 [ 10.  30.  19.  72.  26.]
 [ 11.  67.  19.  14.  34.]
 [ 12.  35.  19.  99.  21.]
 [ 13.  58.  20.  15.  27.]
 [ 14.  24.  20.  77.  30.]
 [ 15.  37.  20.  13.  48.]
 [ 16.  22.  20.  79.  49.]
 [ 17.  35.  21.  35.  33.]
 [ 18.  20.  21.  66.  16.]
 [ 19.  52.  23.  29.  47.]
 [ 20.  35.  23.  98.  30.]
 [ 21.  35.  24.  35.  27.]
 [ 22.  25.  24.  73.  29.]
 [ 23.  46.  25.   5.  35.]
 [ 24.  31.  25.  73.  42.]
 [ 25.  54.  28.  14.  13.]
 [ 26.  29.  28.  82.  41.]
 [ 27.  45.  28.  32.  18.]
 [ 28.  35.  28.  61.  46.]
 [ 29.  40.  29.  31.  30.]
 [ 30.  23.  29.  87.  45.]
 [ 31.  60.  30.   4.  39.]
 [ 32.  21.  30.  73.  13.]
 [ 33.  53.  33.   4.  42.]
 [ 34.  18.  33.  92.  31.]
 [ 35.  49.  33.  14.  50.]
 [ 36.  21.  33.  81