In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
S1 = pd.Series([1, 2, 3, 4], index = ['a', 'b','c','d'])
S2 = pd.Series([11, 22, 33, 44], index = ['a', 'bb' ,'c', 'dd'])
D1 = pd.DataFrame ([S1,S2])

In [3]:
D1

a    b     c    d    bb    dd
0   1.0  2.0   3.0  4.0   NaN   NaN
1  11.0  NaN  33.0  NaN  22.0  44.0

In [2]:
from numpy import genfromtxt

In [3]:
data = genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv',delimiter=',',skip_header = 1)
data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [4]:
index= data[:,1]>320
len(index)

400

In [5]:
student= ["kartik","harsh","anika"]
index_out = [1,2,3]

In [6]:
series = pd.Series(student,index=index_out)
series

1    kartik
2     harsh
3     anika
dtype: object

In [5]:
y = {"Name":["ajey","priya","rahul"], "rollno":[1,2,3], "salary":[12000,13000,6000]}


In [8]:
Name = ["suraj","sourabh","shivani", "sanjana"]
Salary = [3000,45000, 340000,1000]

In [9]:
pd.DataFrame({"Name":Name, "Salary":Salary})

Name  Salary
0    suraj    3000
1  sourabh   45000
2  shivani  340000
3  sanjana    1000

In [6]:
pd.DataFrame(y)

Name  rollno  salary
0   ajey       1   12000
1  priya       2   13000
2  rahul       3    6000

In [10]:
x= pd.DataFrame(y)
x

Name  rollno  salary
0   ajey       1   12000
1  priya       2   13000
2  rahul       3    6000

In [11]:
np.where(index)

(array([  0,   1,   3,   5,   6,   9,  10,  11,  12,  21,  22,  23,  24,
         25,  26,  31,  32,  33,  34,  43,  44,  45,  46,  47,  48,  49,
         52,  53,  54,  64,  65,  66,  69,  70,  71,  72,  75,  76,  81,
         83,  84,  97,  98,  99, 100, 104, 106, 107, 108, 111, 119, 120,
        121, 126, 128, 129, 130, 133, 134, 138, 140, 141, 142, 143, 144,
        147, 148, 150, 151, 152, 153, 154, 164, 165, 171, 172, 173, 174,
        176, 185, 187, 188, 189, 190, 191, 192, 193, 202, 203, 210, 211,
        212, 213, 214, 215, 216, 217, 218, 222, 229, 234, 235, 236, 237,
        242, 243, 245, 248, 249, 253, 254, 257, 258, 259, 260, 263, 264,
        268, 275, 276, 283, 284, 285, 286, 287, 298, 302, 303, 305, 306,
        307, 311, 318, 319, 321, 325, 328, 330, 335, 337, 338, 339, 341,
        351, 356, 359, 360, 361, 362, 365, 371, 372, 373, 380, 382, 384,
        385, 392, 394, 395, 396, 397, 399], dtype=int64),)

In [12]:
a=data[:,1][index]
a

array([337., 324., 322., 330., 321., 323., 325., 327., 328., 325., 328.,
       334., 336., 340., 322., 327., 338., 340., 331., 332., 326., 322.,
       329., 339., 321., 327., 334., 324., 322., 325., 325., 327., 328.,
       332., 336., 321., 329., 327., 340., 322., 340., 331., 332., 323.,
       322., 326., 329., 338., 331., 321., 327., 335., 334., 323., 326.,
       333., 339., 323., 333., 326., 329., 332., 331., 340., 325., 326.,
       339., 334., 332., 321., 324., 326., 329., 322., 334., 322., 323.,
       321., 329., 327., 335., 331., 324., 324., 323., 322., 336., 340.,
       334., 325., 328., 338., 333., 331., 330., 322., 321., 324., 324.,
       324., 330., 326., 325., 329., 324., 325., 328., 324., 321., 335.,
       321., 324., 326., 331., 327., 324., 325., 327., 322., 329., 321.,
       340., 331., 336., 324., 330., 322., 323., 321., 323., 325., 328.,
       324., 327., 323., 326., 324., 327., 325., 332., 323., 324., 326.,
       325., 327., 321., 322., 334., 338., 330., 32

In [13]:
len(a)

163

What is the chance of admission of the students who have a TOEFL score greater than 110? Display the admission chance as a percentage number by multiplying each value in the output by 100.

In [14]:
index1 = data[:,2]>110
x =np.where(index1)

In [15]:
ad = data[:,8][index]*100
ad

array([92., 76., 80., 90., 75., 45., 52., 84., 78., 70., 94., 95., 97.,
       94., 76., 74., 91., 90., 94., 87., 91., 88., 86., 89., 82., 78.,
       78., 72., 70., 52., 55., 61., 78., 94., 96., 93., 72., 74., 96.,
       92., 94., 86., 90., 79., 71., 74., 87., 91., 93., 69., 71., 94.,
       94., 85., 84., 92., 96., 79., 89., 80., 84., 90., 92., 97., 80.,
       83., 96., 93., 94., 86., 79., 80., 81., 78., 89., 86., 89., 87.,
       90., 89., 93., 93., 88., 90., 87., 86., 94., 97., 97., 79., 82.,
       95., 96., 94., 93., 91., 85., 84., 76., 82., 91., 88., 85., 86.,
       70., 76., 81., 80., 77., 93., 85., 78., 77., 90., 87., 70., 75.,
       83., 78., 89., 80., 94., 93., 92., 89., 90., 65., 73., 74., 79.,
       80., 84., 79., 80., 73., 81., 80., 80., 83., 94., 81., 81., 79.,
       73., 79., 81., 85., 93., 91., 86., 89., 95., 79., 78., 82., 96.,
       96., 84., 89., 82., 84., 91., 95.])

In [16]:
data[index1]

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  6.  , 330.  , 115.  , ...,   9.34,   1.  ,   0.9 ],
       [ 12.  , 327.  , 111.  , ...,   9.  ,   1.  ,   0.84],
       ...,
       [395.  , 329.  , 111.  , ...,   9.23,   1.  ,   0.89],
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [17]:
data.shape

(400, 9)

In [18]:
index = (data[:,1]>315) & (data[:,2]>115) &(data[:,7]==1)
index

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,

In [19]:
data[index]

array([[  1.  , 337.  , 118.  ,   4.  ,   4.5 ,   4.5 ,   9.65,   1.  ,
          0.92],
       [ 23.  , 328.  , 116.  ,   5.  ,   5.  ,   5.  ,   9.5 ,   1.  ,
          0.94],
       [ 24.  , 334.  , 119.  ,   5.  ,   5.  ,   4.5 ,   9.7 ,   1.  ,
          0.95],
       [ 25.  , 336.  , 119.  ,   5.  ,   4.  ,   3.5 ,   9.8 ,   1.  ,
          0.97],
       [ 26.  , 340.  , 120.  ,   5.  ,   4.5 ,   4.5 ,   9.6 ,   1.  ,
          0.94],
       [ 33.  , 338.  , 118.  ,   4.  ,   3.  ,   4.5 ,   9.4 ,   1.  ,
          0.91],
       [ 53.  , 334.  , 116.  ,   4.  ,   4.  ,   3.  ,   8.  ,   1.  ,
          0.78],
       [ 71.  , 332.  , 118.  ,   5.  ,   5.  ,   5.  ,   9.64,   1.  ,
          0.94],
       [ 82.  , 340.  , 120.  ,   4.  ,   5.  ,   5.  ,   9.5 ,   1.  ,
          0.96],
       [ 98.  , 331.  , 120.  ,   3.  ,   4.  ,   4.  ,   8.96,   1.  ,
          0.86],
       [ 99.  , 332.  , 119.  ,   4.  ,   5.  ,   4.5 ,   9.24,   1.  ,
          0.9 ],
       [108.  , 338. 

In [20]:
blah = [1,2,3,4,5,6,7,8,121]
data = np.append(data, [blah],axis = 0)

In [21]:
data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95],
       [  1.  ,   2.  ,   3.  , ...,   7.  ,   8.  , 121.  ]])

In [22]:
import pandas as pd
import numpy as np
price = [80121, 48483, 37077, 30660, 68536, 52666, 78703, 51036, 55643, 56990, 39967, 93822, 51406, 93947, 78373, 62765, 47536, 40528, 58780, 83197]

In [23]:
cars_index = np.arange(101,121)

In [24]:
car_ser = pd.Series(price,index = cars_index)
car_ser

101    80121
102    48483
103    37077
104    30660
105    68536
106    52666
107    78703
108    51036
109    55643
110    56990
111    39967
112    93822
113    51406
114    93947
115    78373
116    62765
117    47536
118    40528
119    58780
120    83197
dtype: int64

In [25]:
car_ser.sort_values(ascending = False)[:1]      #highest

114    93947
dtype: int64

In [26]:
car_ser.sort_values(ascending = True)[:1]

104    30660
dtype: int64

In [27]:
car_ser.sort_values(ascending = False)[:5] 

114    93947
112    93822
120    83197
101    80121
107    78703
dtype: int64

In [28]:
x = car_ser.between(30000,40000,inclusive = "both")
car_ser[x]

103    37077
104    30660
111    39967
dtype: int64

In [29]:
condition = car_ser > np.mean(car_ser)
condition

101     True
102    False
103    False
104    False
105     True
106    False
107     True
108    False
109    False
110    False
111    False
112     True
113    False
114     True
115     True
116     True
117    False
118    False
119    False
120     True
dtype: bool

In [30]:
car_ser[condition]

101    80121
105    68536
107    78703
112    93822
114    93947
115    78373
116    62765
120    83197
dtype: int64

In [31]:
new_car_price = pd.Series([34000, 45000, 54000],index = [201,202,203])
new_car_price

201    34000
202    45000
203    54000
dtype: int64

In [32]:
car_ser = pd.concat([car_ser,new_car_price])
car_ser

101    80121
102    48483
103    37077
104    30660
105    68536
106    52666
107    78703
108    51036
109    55643
110    56990
111    39967
112    93822
113    51406
114    93947
115    78373
116    62765
117    47536
118    40528
119    58780
120    83197
201    34000
202    45000
203    54000
dtype: int64

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("DS1_C4_S3_SalesData_Practice.csv")
df

Month Store  Sales       State
0    Jan     A  21080      Alaska
1    Jan     B  32985       Texas
2    Jan     C  22369  California
3    Jan     D  45710     Montana
4    Jan     E  27113  New Mexico
5    Feb     A  27573      Alaska
6    Feb     B  31244       Texas
7    Feb     C  48624  California
8    Feb     D  31768     Montana
9    Feb     E  23851  New Mexico
10   Mar     A  33274      Alaska
11   Mar     B  27215       Texas
12   Mar     C  23475  California
13   Mar     D  21357     Montana
14   Mar     E  22130  New Mexico
15   Apr     A  26073      Alaska
16   Apr     B  45919       Texas
17   Apr     C  30279  California
18   Apr     D  21394     Montana
19   Apr     E  25184  New Mexico
20   May     A  37649      Alaska
21   May     B  44597       Texas
22   May     C  29697  California
23   May     D  28943     Montana
24   May     E  22541  New Mexico
25   Jun     A  28500      Alaska
26   Jun     B  32896       Texas
27   Jun     C  30200  California
28   Jun     D  37098     Montana
29   Jun     E  41098  New Mexico

In [3]:
df["Month"] =[1,2,3]

ValueError: Length of values (3) does not match length of index (30)

In [35]:
cal = df[df["State"]=="California"]
cal

Month Store  Sales       State
2    Jan     C  22369  California
7    Feb     C  48624  California
12   Mar     C  23475  California
17   Apr     C  30279  California
22   May     C  29697  California
27   Jun     C  30200  California

In [36]:
cal.sort_values(by="Sales")

Month Store  Sales       State
2    Jan     C  22369  California
12   Mar     C  23475  California
22   May     C  29697  California
27   Jun     C  30200  California
17   Apr     C  30279  California
7    Feb     C  48624  California

In [37]:
high = cal.sort_values(by="Sales",ascending=False)
high[["Month"]][:1]

Month
7   Feb

In [38]:
high

Month Store  Sales       State
7    Feb     C  48624  California
17   Apr     C  30279  California
27   Jun     C  30200  California
22   May     C  29697  California
12   Mar     C  23475  California
2    Jan     C  22369  California

In [39]:
import pandas as pd
import numpy as np

In [7]:
customer = pd.read_excel("DS1_C4_S4_Customer_Data_Concept.xlsx", sheet_name = 0)
customer

Cust_ID      Name
0      101    Olivia
1      102  Will LLC
2      103    Sophia
3      104  Isabella

In [8]:
order = pd.read_excel("DS1_C4_S4_Customer_Data_Concept.xlsx", sheet_name = 1)
order

Order_ID  Cust_ID  Order
0       222      101    789
1       223      102    465
2       224      103    674
3       225      104    564
4       226      105    589

In [9]:
customer.set_index("Cust_ID").join(order.set_index("Cust_ID"), on="Cust_ID", how="inner")

Name  Order_ID  Order
Cust_ID                           
101        Olivia       222    789
102      Will LLC       223    465
103        Sophia       224    674
104      Isabella       225    564

In [42]:
# inner join

In [43]:
customer.set_index("Cust_ID").join(order.set_index("Cust_ID"), on="Cust_ID", how = "inner")

Name  Order_ID  Order
Cust_ID                           
101        Olivia       222    789
102      Will LLC       223    465
103        Sophia       224    674
104      Isabella       225    564

In [44]:
customer.merge(order, on="Cust_ID", how= "inner")

Cust_ID      Name  Order_ID  Order
0      101    Olivia       222    789
1      102  Will LLC       223    465
2      103    Sophia       224    674
3      104  Isabella       225    564

In [45]:
customer.set_index("Cust_ID").join(order.set_index("Cust_ID"), on = "Cust_ID", how="left")

Name  Order_ID  Order
Cust_ID                           
101        Olivia       222    789
102      Will LLC       223    465
103        Sophia       224    674
104      Isabella       225    564

In [46]:
customer.set_index("Cust_ID").join(order.set_index("Cust_ID"), on = "Cust_ID", how="right")

Cust_ID      Name  Order_ID  Order
101.0      101    Olivia       222    789
102.0      102  Will LLC       223    465
103.0      103    Sophia       224    674
104.0      104  Isabella       225    564
NaN        105       NaN       226    589

In [47]:
name = ["ajay","vijay","amar"]
wts = ["60kg","60kg","60kg"]
dob = ['10/05/1999','2/21/1997','12/30/2000']

In [48]:
student = pd.DataFrame({"Name":name, "Weight": wts, "DOB":dob})
student

Name Weight         DOB
0   ajay   60kg  10/05/1999
1  vijay   60kg   2/21/1997
2   amar   60kg  12/30/2000

In [49]:
student["DOB"]  = pd.to_datetime(student["DOB"] )
student.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Name    3 non-null      object        
 1   Weight  3 non-null      object        
 2   DOB     3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes


In [50]:
student['Weight'] = student["Weight"].str.replace("kg","")
student

Name Weight        DOB
0   ajay     60 1999-10-05
1  vijay     60 1997-02-21
2   amar     60 2000-12-30

In [51]:
student  = student.astype({"Weight":float})
student.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Name    3 non-null      object        
 1   Weight  3 non-null      float64       
 2   DOB     3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 204.0+ bytes


In [52]:
student.replace(to_replace=['ajay'], value ="Deepak")

Name  Weight        DOB
0  Deepak    60.0 1999-10-05
1   vijay    60.0 1997-02-21
2    amar    60.0 2000-12-30

In [53]:
df1.groupby(by = ["Blood_pressure_check"])["age"].mean()

NameError: name 'df1' is not defined

In [ ]:
df1.groupby(by=["Gener"])["bmi"].max()

In [ ]:
df1.groupby(by = ["region"])["claim"].sum().sort_values(ascending = False)[:3]

In [ ]:
pd.pivot_table(df1, index= ["region"], values=["claim"])

In [ ]:
pd.pivot_table(df1, index= ["region"], values=["claim"], aggfunc = "min")

In [ ]:
pd.crosstab(df1.region, df1.gender, rownames = ['region'], colnames= ["gender"])

In [ ]:
pd.crosstab(df1.region, df1.gender, rownames = ['region'], colnames= ["gender"], values =df1['claim'], aggfunc=['sum'])

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
activity = pd.read_csv("DS1_C4_S5_Activity_Lifestyle_Data_Concept.csv")
activity

In [ ]:
plt.pie(x=activity["Average days in a month"], labels= activity["Activity"], autopct="%0.2f%%")
plt.show()

In [ ]:
building = pd.read_csv("DS1_C4_S5_Building_Data_Concept.csv")
building

In [ ]:
plt.barh(building["Building"], building["Height (in Feet)"])

In [ ]:
revenue =pd.read_csv("DS1_C4_S5_Revenue_Data_Concept.csv")
revenue

In [ ]:
revenue.plot(x= "Brand Name",kind = "bar",
            stacked = False,
            xlabel=("Brand Name"))

In [ ]:
quaterly = pd.read_csv("DS1_C4_S5_Sales_Data_Concept.csv")
quaterly

In [ ]:
plt.figure(figsize=(15,5))                                                      #combinded chart of bar and line
plt.plot(quaterly["Quarter"],quaterly["Revenue (in Million)"], color="black")
plt.bar(quaterly["Quarter"],quaterly["Revenue (in Million)"], color = "maroon")

In [ ]:
persons = pd.read_csv("DS1_C4_S5_Person_Data_Concept.csv")
persons

In [ ]:
plt.hist(persons["Weight"], bins=19)

The company wants to analyze gender equality across several departments. Display the department-wise total number of male and female employees using a DataFrame. Hints: Summarize the department- and gender-wise count of employees. Create a DataFrame with all department names and the respective male and female counts.

In [54]:
df = pd.read_excel("DS1_C4_S5_Employee_Data_Practice.xlsx",sheet_name = 0)
df

Employee_Code   Gender Department  Annual Salary ($)  Age  Work_Experience
0             1010    Male        IT               27000   22                0
1             1011  Female        IT               48000   27                4
2             1012    Male      Sales              75000   31                7
3             1013    Male      Sales              61000   29                6
4             1014  Female    Finance              45000   27                4
..             ...     ...        ...                ...  ...              ...
65            1074  Female         HR              82500   43               13
66            1075    Male      Sales              53500   28                5
67            1076  Female         HR              57000   29                6
68            1077    Male      Sales              66500   33                7
69            1078    Male    Finance              92000   45               19

[70 rows x 6 columns]

In [55]:
pd.crosstab(df.Department, df.Gender, rownames = ["Department"], colnames=["Gender"])

Gender      Female  Male
Department              
Finance          2    11
HR              11     4
IT              10    12
Sales            4    16

In [ ]:
pd.DataFrame({"Name":})

In [60]:
import math
import os
import random
import re
import sys


n = int(input())
if n % 2 !=0:
    print("weird")
elif n%2==0 and 2 <= n <= 5:
    print("Not Weird")
elif n%2==0 and 6 <= n <= 20:
    print("Weird")
elif n%2==0 and n>20:
    print("Not Weird")


26
Not Weird


In [4]:
import pandas as pd
lod = [{"a": 1,"b": 2}, {"a":5, "b":10, "c":20}]
d1 = pd.DataFrame(lod)

In [5]:
d1

a   b     c
0  1   2   NaN
1  5  10  20.0

In [ ]:
DF.loc

In [1]:
import statistics as st

nums = [1, 2, 3, 5, 7, 9, 7, 2, 7, 6]
result = st.stdev(nums)
print(result)

2.7264140062238043


In [2]:
import statistics as st 
st. mean ([-2, -4, 7])

0.3333333333333333

In [17]:
d1 = {"kartik":1, "harsh":2 , "anika":3, "jeevika":4}
d2 = {"arjun": 5, "sourabh":6, "rishabh":3, "rahul":4}

In [2]:
type(d1)

dict

In [21]:
suumofkeysd1 = d1.get("kartik") +d1.get("harsh")  + d1.get("anika")  +d1.get("jeevika")   

In [22]:
suumofkeysd1 

10

In [20]:
sumofd2 = d2.get("arjun") +d2.get("sourabh")  + d2.get("rishabh")  +d2.get("rahul") 

In [24]:
sumofd2

18

In [23]:
suumofkeysd1 + sumofd2

28

In [10]:
pd.DataFrame({"city":["bangalore","delhi", "bijnor"], "Name":["kartik","arjun","harsh"]})

city    Name
0  bangalore  kartik
1      delhi   arjun
2     bijnor   harsh

In [53]:
def factorial():
    n=int(input("enter a number"))
    if n==0:
        return 1
    else:
        return n*factorial(n-1)
        

In [54]:
factorial()

enter a number2


TypeError: factorial() takes 0 positional arguments but 1 was given

In [36]:
factorial(6)

720

In [5]:
import pandas as pd
import numpy as np


In [10]:
df = pd.DataFrame({"id":[1,2,3,4], "Name":["a","b","c","d"], "marks":[10,20,30,40]})

In [11]:
df

id Name  marks
0   1    a     10
1   2    b     20
2   3    c     30
3   4    d     40

In [38]:
df.iloc[0:4,0:4]

id Name  marks       city
0   1    a     10      delhi
1   2    b     20  bangalore
2   3    c     30     kanpur
3   4    d     40     meerut

In [24]:
df.loc[0:3,"id":"Name"]

id Name
0   1    a
1   2    b
2   3    c
3   4    d

In [25]:
df

id Name  marks
0   1    a     10
1   2    b     20
2   3    c     30
3   4    d     40

In [26]:
df["city"] = ["delhi","bangalore","kanpur", "meerut"]

In [27]:
df

id Name  marks       city
0   1    a     10      delhi
1   2    b     20  bangalore
2   3    c     30     kanpur
3   4    d     40     meerut

In [28]:
l1 = [10,20,30,40,50]

In [42]:
l1.reverse()
l1

[50, 40, 30, 20, 10]

In [34]:
l1

[50, 40, 30, 20, 10]

In [43]:
l1.reverse()

In [44]:
l1

[10, 20, 30, 40, 50]

In [45]:
l1[::-1]

[50, 40, 30, 20, 10]

In [59]:
def factorial(n):
    # Base case: factorial of 0 is 1
    if n == 0:
        return 1
    else:
        # Recursive case: n! = n * (n-1)!
        return n * factorial(n - 1)

# Ask user to enter a number
number = int(input("Enter a non-negative integer to calculate its factorial: "))

# Check if the number is non-negative
if number < 0:
    print("Factorial is not defined for negative numbers.")
else:
    # Calculate the factorial of the input number
    result = factorial(number)
    print(result)

Enter a non-negative integer to calculate its factorial: 2
2


In [71]:
l4 = [20,30,40]
l5 = [50,60]

In [66]:
l2.append(l3)

In [67]:
l2

[20, 30, 40, [50, 60]]

In [ ]:
for i in l4:
    l4.append(i)
print(l4)